### PR TITLE
Matt project2

### PR DESCRIPTION
**Pull request by matt-c-knight**

### CODE REVIEW

**Comment by mmoritz8** [comment]
hey, I didn't realize that this never resolved bc we had to do more to merge it. So! in class today we can do this together. I'm more than happy to go through and see what's necessary cause there are 25 files that were changed lol

**Comment by mmoritz8** [comment]
Oh wait! NVM

**Comment by mmoritz8** [comment]
... shit

**Comment by mmoritz8** [comment]
ok ok only a few

**Comment by matt-c-knight** [comment]
Added authentication

**Pull request closed without merging**
